name: Test build
on: [workflow_call, workflow_dispatch]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
        with:
         egress-policy: block
         allowed-endpoints: >
           95s5acprodeus1file6.blob.core.windows.net:443
           api.github.com:443
           artifactcache.actions.githubusercontent.com:443
           github.com:443
           index.rubygems.org:443
           pipelines.actions.githubusercontent.com:443
           rubygems.org:443
      - name: Checkout repo
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - name: Setup ruby
        uses: ruby/setup-ruby@c7079efafd956afb5d823e8999c2506e1053aefa
        with:
          ruby-version: 3.1.2
      - name: Build Jekyll
        uses: limjh16/jekyll-action-ts@9edf74e2e5aaa10d272c427efb8702a45a70a0b2
        with:
          enable_cache: true
