name: mcfunction Release
on: 
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: "The tag to create for your release."
      path:
        required: false
        type: string
        default: ./
        description: "The path to the directory your pack.mcmeta is in. Defaults to the root directory."
      files:
        required: false
        type: string
        default: |
          data/
          pack.mcmeta
          pack.png
          LICENSE.md
        description: "The files that should be uploaded to the release and as artifacts. Defaults to data/, pack.mcmeta, pack.png, and LICENSE.md."
      mc_version:
        required: false
        type: string
        default: 1.19
        description: "The Minecraft version your pack is meant for. Defaults to 1.19, valid versions are any major version 1.16+."
    secrets:
      GH_TOKEN:
        required: true
        description: "A PAT (personal access token) with `repo` scope."
permissions:
  contents: read

jobs:
   upload-normal:
    name: Create non-optimized datapack
    runs-on: ubuntu-latest
    steps:
     - name: Harden Runner
       uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95
       with:
         egress-policy: audit
     - name: Clone repository
       uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
       with:
         fetch-depth: 0
     - name: Check commands
       uses: mcbeet/check-commands@740e5fb3c385a5a5775f9ab6c963745200cb71aa
       with:
          source: ${{ inputs.path }}
          minecraft: ${{ inputs.mc_version }}
     - name: Check JSON
       uses: ocular-d/json-linter@7d3716a34bcd6fcc5b3b38141a21b9e02da6531d
     - name: Upload artifact
       uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
       with:
         path: |
             assets/
             data/
             pack.mcmeta
             pack.png
             LICENSE.md
         name: ${{ github.repository }} ${{ inputs.version }}

         
   upload-optimized-datapack:
    permissions:
      actions: read  # for ComunidadAylas/PackSquash-action to get latest artifact
    name: Optimize datapack
    runs-on: ubuntu-latest
    needs: upload-normal
    steps:
     - name: Harden Runner
       uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95
       with:
         egress-policy: audit

     - name: Download normal pack
       uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
       with:
         name: ${{ github.repository }} ${{ inputs.version }}
         path: ./
     - name: Run PackSquash
       uses: ComunidadAylas/PackSquash-action@cdeba7365a1491b436b1a9c381d63b5ee6c27f2e
       with:
          path: ./
          token: ${{ secrets.GITHUB_TOKEN }}
          minify_json_files: true
          validate_pack_metadata_file: true
          allow_optifine_mod: true
          delete_bloat_json_keys: true
          artifact_name: '[UNZIP ME] optimized-${{ github.repository }} ${{ inputs.version }}'
          never_store_squash_times: true

   create-release:
     permissions:
       contents: write  # for softprops/action-gh-release to create GitHub release
       issues: read  # for heinrichreimer/github-changelog-generator-action to fetch issues and labels
       pull-requests: read  # for heinrichreimer/github-changelog-generator-action to fetch PRs and labels
     name: Create release
     needs: [upload-normal,upload-optimized-datapack]
     runs-on: ubuntu-latest
     steps:
       - name: Harden Runner
         uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95
         with:
           egress-policy: audit
       - name: Checkout repo
         uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
         with:
           token: ${{ secrets.GH_TOKEN }}
       - name: Generate release changelog
         uses: heinrichreimer/github-changelog-generator-action@6f5b9494dd265d6fb7243a10c53dc0169c55f247
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           dateFormat: '%m/%d/%Y'
       - name: Make directory
         run: mkdir changelog
       - name: Generate release changelog (Single tag)
         uses: heinrichreimer/github-changelog-generator-action@6f5b9494dd265d6fb7243a10c53dc0169c55f247
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           dateFormat: '%m/%d/%Y'
           onlyLastTag: true
           output: /changelog/CHANGELOG.md
       - name: Download normal pack
         uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
         with:
           name: ${{ github.repository }} ${{ inputs.version }}
       - name: Zip pack
         run: zip '${{ github.repository }} ${{ inputs.version }}' -r ${{ inputs.files }}
       - name: Delete datapack
         run: rm -r ${{ inputs.files }}
       - name: Download optimized pack
         uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
         with:
           name: optimized-${{ github.repository }} ${{ inputs.version }}
       - name: Zip optimized pack
         run: |
           mkdir packsquash
           unzip -f pack.zip -d /packsquash/
           mv LICENSE.md /packsquash/
           cd packsquash
           zip -r 'optimized-${{ github.repository }} ${{ inputs.version }}' . -i ${{ inputs.files }}
           mv 'optimized-${{ github.repository }} ${{ inputs.version }}' ..
           cd ..
       - name: Release
         uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
         with:
           files: |
             *.zip
           body_path: /changelog/CHANGELOG.md
       - name: Commit changes
         run: |
            echo ${GITHUB_REF#refs/*/}
            git config --local user.name "actions-user"
            git config --local user.email "action@github.com"
            git add CHANGELOG.md
            git commit -m "[ci skip] Updated CHANGELOG.md for ${{ inputs.version }}"
            git push origin HEAD:master
