# To use this, you will need to specify the path to your datapack/mcfunction files and the version.
# The job will fail if you do not provide these.

name: mcfunction CI
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: "The release number to use in the artifact name. `-SNAPSHOT` will be added to the end."
      path:
        required: false
        type: string
        default: ./
        description: "The path to the directory your pack.mcmeta is in. Defaults to the root directory."
      files:
        required: false
        type: string
        default: |
          data/
          pack.mcmeta
          pack.png
          LICENSE.md
        description: "The files that should be uploaded as artifacts. Defaults to data/, pack.mcmeta, pack.png, and LICENSE.md."
      mc_version:
        required: false
        type: string
        default: 1.19
        description: "The Minecraft version your pack is meant for. Defaults to 1.19, valid versions are any major version 1.16+."
jobs:
  build-main:
    name: Main mcfunction CI
    runs-on: ubuntu-latest
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
        with:
         egress-policy: block
         allowed-endpoints: >
          artifactcache.actions.githubusercontent.com:443
          files.pythonhosted.org:443
          gel7acprodeus1file0.blob.core.windows.net:443
          github.com:443
          pipelines.actions.githubusercontent.com:443
          pypi.org:443
          api.github.com:443
          prtcacprodeus2file7.blob.core.windows.net:443
      - name: Checkout repo
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Dependency Review
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@0efb1d1d84fc9633afcdaad14c485cbbc90ef46c
      - name: Check commands
        uses: mcbeet/check-commands@740e5fb3c385a5a5775f9ab6c963745200cb71aa
        with:
          source: .
          minecraft: ${{ inputs.mc_version }}
      - name: Check JSON
        uses: ocular-d/json-linter@7d3716a34bcd6fcc5b3b38141a21b9e02da6531d
      - name: Get repository name without owner's name
        id: repo_name
        run: echo ::set-output name=REPO::${GITHUB_REPOSITORY#*/}
      - name: Compile and upload
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        with:
          name: ${{ steps.repo_name.outputs.repo }} ${{ inputs.version }}-SNAPSHOT
          path: |
            ${{ inputs.files }}
          if-no-files-found: error

  build-packsquash:
    permissions:
      actions: read  # for ComunidadAylas/PackSquash-action to get latest artifact
      contents: read  # for actions/checkout to fetch code
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    name: mcfunction CI with PackSquash
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            artifactcache.actions.githubusercontent.com:443
            gel7acprodeus1file0.blob.core.windows.net:443
            github.com:443
            objects.githubusercontent.com:443
            prtcacprodeus2file7.blob.core.windows.net:443
      - name: Checkout repo
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          fetch-depth: 0
      - name: Get repository name without owner's name
        id: repo_name
        run: echo ::set-output name=REPO::${GITHUB_REPOSITORY#*/}
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@5e0e65b4a8d89735b64e0f20564179ed3dc7855f
        with:
          path: ${{ inputs.path }}
          token: ${{ secrets.GITHUB_TOKEN }}
          minify_json_files: true
          validate_pack_metadata_file: true
          allow_optifine_mod: true
          delete_bloat_json_keys: true
          artifact_name: '[UNZIP ME] optimized-${{ steps.repo_name.outputs.repo }} ${{ inputs.version }}-SNAPSHOT'
