name: Python CI with a matrix using pipenv
on: [workflow_call, workflow_dispatch]
permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read
jobs:
  build:
    name: Main CI Build
    runs-on: ${{ matrix.os }}
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          path: ~/.cache/pip
        - os: macos-latest
          path: ~/Library/Caches/pip
        - os: windows-latest
          path: ~\AppData\Local\pip\Cache
    steps:
    - name: Harden Runner
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95
      with:
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          artifactcache.actions.githubusercontent.com:443
          github.com:443
          pypi.org:443
          y2oiacprodeus2file6.blob.core.windows.net:443
          files.pythonhosted.org
    - name: Checkout repo
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    - name: Set up Python 3.10
      uses: actions/setup-python@b55428b1882923874294fa556849718a1d7f2ca5
      with:
        python-version: "3.10"
    - name: Install pipenv
      run: pip install pipenv
    - name: Cache dependencies
      uses: actions/cache@ac8075791e805656e71b4ba23325ace9e3421120
      with:
        path: ${{ matrix.path }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile') }}
        restore-keys: |
         ${{ runner.os }}-pip-
    - name: Install dependencies
      run: 
        python -m pipenv install
        pip install flake8 pytest
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
